apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    name: flask-service
    app: capstone-webapp
spec:
  type: NodePort
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30004
  selector:
    name: flask-pod
    app: capstone-webapp