---
- name: Play for deploying jenkins on EC2 instance
  hosts: EC2
#  remote_user: ubuntu
  become: true

  vars:
    ansible_inventory: ./inventory.ini

  tasks:
    - name: Download and install Jenkins keyring
      ansible.builtin.shell: |
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null &&
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true

    - name: Install openJDK
      ansible.builtin.apt:
        pkg:
        - openjdk-11-jre
        state: "present"

    - name: Install Jenkins
      ansible.builtin.apt:
        pkg:
        - jenkins
        state: "present"

    - name: Stop jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: stopped

    - name: Download Jenkins backup to /var/lib/
      ansible.builtin.get_url:
        url: https://filebin.net/002e4kysvg7kl52v/jenkins_backup.tar
        dest: /var/lib/jenkins_backup.tar
        checksum: sha256:5467967b867ed13e89394cdda428dae143273151429ac9fd86bc19c5ecee34cd

    - name: Extract Archive to /var/lib/
      ansible.builtin.unarchive:
        src: /var/lib/jenkins_backup.tar
        dest: /var/lib/
        remote_src: true

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started